services:
  helloworld: # not in use currently
    build:
      context: ./helloworld
    container_name: micro_helloworld
    environment:
      MICRO_SERVICE_ADDRESS: micro-helloworld:7000 # maybe 0.0.0.0:7000?
      MICRO_BROKER_ADDRESS: micro-server:10001
    expose:
      - "7000"
    networks:
      micronetwork:
        aliases:
          - micro-helloworld
    depends_on:
      - server
  server:
    image: micro/micro
    command: server
    container_name: micro_server
    #environment:
    #MICRO_SERVER_ADDRESS: 0.0.0.0:8080
    #MICRO_BROKER_ADDRESS: 0.0.0.0:10001
    #MICRO_REGISTRY: mdns
    ports:
      - "4000:8080"
      - "8081:8081/tcp"
    volumes:
      - ./helloworld:/helloworld
      - ./Makefile:/Makefile
    networks:
      micronetwork:
        aliases:
          - micro-server
networks:
  micronetwork:
    name: micronetwork
