version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
      DEFAULT_DB: teste
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "6.5"
    #    reservations:
    #      cpus: "6.5"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
