services:
  hello-world:
    build:
      context: ./hello-world
    expose:
      - "3000"
    networks:
      nestnetwork:
        aliases:
          - nestjs-hello-world
  gateway:
    build:
      context: ./gateway
    ports:
      - "4000:4000"
    networks:
      nestnetwork:
        aliases:
          - nestjs-gateway
    depends_on:
      - hello-world
networks:
  nestnetwork:
    name: nestnetwork
