services:
  server:
    image: micro/micro
    command: server
    container_name: micro_server
    ports:
      - "4000:8080"
      - "8081:8081/tcp"
    volumes:
      - ./helloworld:/helloworld
      - ./Makefile:/Makefile
    networks:
      micronetwork:
        aliases:
          - micro-server
networks:
  micronetwork:
    name: micronetwork
