version: '3.5'

services:
  postgres_container:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
      DEFAULT_DB: teste
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres_container
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge